import { getDb } from "../api/queries/connection";
import { exchangeRates, supportedCountries } from "./schema";

async function seedExchangeRates() {
  const db = getDb();
  const existing = await db.select().from(exchangeRates).limit(1);
  if (existing.length > 0) return;

  const commonRates = [
    { from: "USD", to: "EUR", rate: "0.85" },
    { from: "USD", to: "GBP", rate: "0.73" },
    { from: "USD", to: "JPY", rate: "110.50" },
    { from: "USD", to: "CAD", rate: "1.25" },
    { from: "USD", to: "AUD", rate: "1.35" },
    { from: "USD", to: "CHF", rate: "0.92" },
    { from: "USD", to: "CNY", rate: "6.45" },
    { from: "USD", to: "MXN", rate: "20.15" },
    { from: "USD", to: "INR", rate: "74.50" },
    { from: "USD", to: "BRL", rate: "5.25" },
    { from: "USD", to: "ZAR", rate: "14.80" },
    { from: "USD", to: "SEK", rate: "8.55" },
    { from: "USD", to: "NOK", rate: "8.75" },
    { from: "USD", to: "DKK", rate: "6.35" },
    { from: "USD", to: "PLN", rate: "3.85" },
    { from: "USD", to: "TRY", rate: "8.65" },
    { from: "USD", to: "RUB", rate: "73.50" },
    { from: "USD", to: "KRW", rate: "1180.00" },
    { from: "USD", to: "SGD", rate: "1.35" },
    { from: "USD", to: "HKD", rate: "7.75" },
    { from: "EUR", to: "USD", rate: "1.18" },
    { from: "EUR", to: "GBP", rate: "0.86" },
    { from: "GBP", to: "USD", rate: "1.37" },
    { from: "GBP", to: "EUR", rate: "1.16" },
  ];

  for (const rate of commonRates) {
    await db.insert(exchangeRates).values({
      fromCurrency: rate.from,
      toCurrency: rate.to,
      rate: rate.rate,
      source: "seed",
    });
  }
  console.log("Exchange rates seeded");
}

async function seedCountries() {
  const db = getDb();
  const existing = await db.select().from(supportedCountries).limit(1);
  if (existing.length > 0) return;

  const countries = [
    { code: "US", name: "United States", currency: "USD", currencyName: "US Dollar", flag: "🇺🇸", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "GB", name: "United Kingdom", currency: "GBP", currencyName: "British Pound", flag: "🇬🇧", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "DE", name: "Germany", currency: "EUR", currencyName: "Euro", flag: "🇩🇪", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "FR", name: "France", currency: "EUR", currencyName: "Euro", flag: "🇫🇷", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "IT", name: "Italy", currency: "EUR", currencyName: "Euro", flag: "🇮🇹", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "ES", name: "Spain", currency: "EUR", currencyName: "Euro", flag: "🇪🇸", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "CA", name: "Canada", currency: "CAD", currencyName: "Canadian Dollar", flag: "🇨🇦", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "AU", name: "Australia", currency: "AUD", currencyName: "Australian Dollar", flag: "🇦🇺", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "JP", name: "Japan", currency: "JPY", currencyName: "Japanese Yen", flag: "🇯🇵", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "CN", name: "China", currency: "CNY", currencyName: "Chinese Yuan", flag: "🇨🇳", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "IN", name: "India", currency: "INR", currencyName: "Indian Rupee", flag: "🇮🇳", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "BR", name: "Brazil", currency: "BRL", currencyName: "Brazilian Real", flag: "🇧🇷", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "MX", name: "Mexico", currency: "MXN", currencyName: "Mexican Peso", flag: "🇲🇽", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "ZA", name: "South Africa", currency: "ZAR", currencyName: "South African Rand", flag: "🇿🇦", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "NG", name: "Nigeria", currency: "NGN", currencyName: "Nigerian Naira", flag: "🇳🇬", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "KE", name: "Kenya", currency: "KES", currencyName: "Kenyan Shilling", flag: "🇰🇪", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "PH", name: "Philippines", currency: "PHP", currencyName: "Philippine Peso", flag: "🇵🇭", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "ID", name: "Indonesia", currency: "IDR", currencyName: "Indonesian Rupiah", flag: "🇮🇩", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "TH", name: "Thailand", currency: "THB", currencyName: "Thai Baht", flag: "🇹🇭", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "KR", name: "South Korea", currency: "KRW", currencyName: "South Korean Won", flag: "🇰🇷", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "RU", name: "Russia", currency: "RUB", currencyName: "Russian Ruble", flag: "🇷🇺", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TR", name: "Turkey", currency: "TRY", currencyName: "Turkish Lira", flag: "🇹🇷", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "PL", name: "Poland", currency: "PLN", currencyName: "Polish Zloty", flag: "🇵🇱", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "SE", name: "Sweden", currency: "SEK", currencyName: "Swedish Krona", flag: "🇸🇪", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "NO", name: "Norway", currency: "NOK", currencyName: "Norwegian Krone", flag: "🇳🇴", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "DK", name: "Denmark", currency: "DKK", currencyName: "Danish Krone", flag: "🇩🇰", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "CH", name: "Switzerland", currency: "CHF", currencyName: "Swiss Franc", flag: "🇨🇭", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "NL", name: "Netherlands", currency: "EUR", currencyName: "Euro", flag: "🇳🇱", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "BE", name: "Belgium", currency: "EUR", currencyName: "Euro", flag: "🇧🇪", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "AT", name: "Austria", currency: "EUR", currencyName: "Euro", flag: "🇦🇹", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "PT", name: "Portugal", currency: "EUR", currencyName: "Euro", flag: "🇵🇹", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "GR", name: "Greece", currency: "EUR", currencyName: "Euro", flag: "🇬🇷", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "IE", name: "Ireland", currency: "EUR", currencyName: "Euro", flag: "🇮🇪", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "FI", name: "Finland", currency: "EUR", currencyName: "Euro", flag: "🇫🇮", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "NZ", name: "New Zealand", currency: "NZD", currencyName: "New Zealand Dollar", flag: "🇳🇿", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "SG", name: "Singapore", currency: "SGD", currencyName: "Singapore Dollar", flag: "🇸🇬", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "HK", name: "Hong Kong", currency: "HKD", currencyName: "Hong Kong Dollar", flag: "🇭🇰", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "MY", name: "Malaysia", currency: "MYR", currencyName: "Malaysian Ringgit", flag: "🇲🇾", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "VN", name: "Vietnam", currency: "VND", currencyName: "Vietnamese Dong", flag: "🇻🇳", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "PK", name: "Pakistan", currency: "PKR", currencyName: "Pakistani Rupee", flag: "🇵🇰", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "BD", name: "Bangladesh", currency: "BDT", currencyName: "Bangladeshi Taka", flag: "🇧🇩", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "EG", name: "Egypt", currency: "EGP", currencyName: "Egyptian Pound", flag: "🇪🇬", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "MA", name: "Morocco", currency: "MAD", currencyName: "Moroccan Dirham", flag: "🇲🇦", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GH", name: "Ghana", currency: "GHS", currencyName: "Ghanaian Cedi", flag: "🇬🇭", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "TZ", name: "Tanzania", currency: "TZS", currencyName: "Tanzanian Shilling", flag: "🇹🇿", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "UG", name: "Uganda", currency: "UGX", currencyName: "Ugandan Shilling", flag: "🇺🇬", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "RW", name: "Rwanda", currency: "RWF", currencyName: "Rwandan Franc", flag: "🇷🇼", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "ET", name: "Ethiopia", currency: "ETB", currencyName: "Ethiopian Birr", flag: "🇪🇹", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CO", name: "Colombia", currency: "COP", currencyName: "Colombian Peso", flag: "🇨🇴", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "PE", name: "Peru", currency: "PEN", currencyName: "Peruvian Sol", flag: "🇵🇪", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "CL", name: "Chile", currency: "CLP", currencyName: "Chilean Peso", flag: "🇨🇱", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "AR", name: "Argentina", currency: "ARS", currencyName: "Argentine Peso", flag: "🇦🇷", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "UY", name: "Uruguay", currency: "UYU", currencyName: "Uruguayan Peso", flag: "🇺🇾", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "UA", name: "Ukraine", currency: "UAH", currencyName: "Ukrainian Hryvnia", flag: "🇺🇦", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "RO", name: "Romania", currency: "RON", currencyName: "Romanian Leu", flag: "🇷🇴", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "CZ", name: "Czech Republic", currency: "CZK", currencyName: "Czech Koruna", flag: "🇨🇿", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "HU", name: "Hungary", currency: "HUF", currencyName: "Hungarian Forint", flag: "🇭🇺", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "BG", name: "Bulgaria", currency: "BGN", currencyName: "Bulgarian Lev", flag: "🇧🇬", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "HR", name: "Croatia", currency: "EUR", currencyName: "Euro", flag: "🇭🇷", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "SI", name: "Slovenia", currency: "EUR", currencyName: "Euro", flag: "🇸🇮", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "SK", name: "Slovakia", currency: "EUR", currencyName: "Euro", flag: "🇸🇰", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "LT", name: "Lithuania", currency: "EUR", currencyName: "Euro", flag: "🇱🇹", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "LV", name: "Latvia", currency: "EUR", currencyName: "Euro", flag: "🇱🇻", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "EE", name: "Estonia", currency: "EUR", currencyName: "Euro", flag: "🇪🇪", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "IS", name: "Iceland", currency: "ISK", currencyName: "Icelandic Krona", flag: "🇮🇸", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "MT", name: "Malta", currency: "EUR", currencyName: "Euro", flag: "🇲🇹", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "CY", name: "Cyprus", currency: "EUR", currencyName: "Euro", flag: "🇨🇾", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "LU", name: "Luxembourg", currency: "EUR", currencyName: "Euro", flag: "🇱🇺", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "MK", name: "North Macedonia", currency: "MKD", currencyName: "Macedonian Denar", flag: "🇲🇰", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AL", name: "Albania", currency: "ALL", currencyName: "Albanian Lek", flag: "🇦🇱", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "RS", name: "Serbia", currency: "RSD", currencyName: "Serbian Dinar", flag: "🇷🇸", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "ME", name: "Montenegro", currency: "EUR", currencyName: "Euro", flag: "🇲🇪", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", currencyName: "Bosnia Convertible Mark", flag: "🇧🇦", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GE", name: "Georgia", currency: "GEL", currencyName: "Georgian Lari", flag: "🇬🇪", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AM", name: "Armenia", currency: "AMD", currencyName: "Armenian Dram", flag: "🇦🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AZ", name: "Azerbaijan", currency: "AZN", currencyName: "Azerbaijani Manat", flag: "🇦🇿", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "KZ", name: "Kazakhstan", currency: "KZT", currencyName: "Kazakhstani Tenge", flag: "🇰🇿", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "UZ", name: "Uzbekistan", currency: "UZS", currencyName: "Uzbekistani Som", flag: "🇺🇿", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "KG", name: "Kyrgyzstan", currency: "KGS", currencyName: "Kyrgystani Som", flag: "🇰🇬", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TJ", name: "Tajikistan", currency: "TJS", currencyName: "Tajikistani Somoni", flag: "🇹🇯", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TM", name: "Turkmenistan", currency: "TMT", currencyName: "Turkmenistani Manat", flag: "🇹🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MN", name: "Mongolia", currency: "MNT", currencyName: "Mongolian Tugrik", flag: "🇲🇳", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "NP", name: "Nepal", currency: "NPR", currencyName: "Nepalese Rupee", flag: "🇳🇵", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "LK", name: "Sri Lanka", currency: "LKR", currencyName: "Sri Lankan Rupee", flag: "🇱🇰", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "MM", name: "Myanmar", currency: "MMK", currencyName: "Myanmar Kyat", flag: "🇲🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "KH", name: "Cambodia", currency: "KHR", currencyName: "Cambodian Riel", flag: "🇰🇭", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "LA", name: "Laos", currency: "LAK", currencyName: "Lao Kip", flag: "🇱🇦", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BT", name: "Bhutan", currency: "BTN", currencyName: "Bhutanese Ngultrum", flag: "🇧🇹", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MV", name: "Maldives", currency: "MVR", currencyName: "Maldivian Rufiyaa", flag: "🇲🇻", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AF", name: "Afghanistan", currency: "AFN", currencyName: "Afghan Afghani", flag: "🇦🇫", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "IQ", name: "Iraq", currency: "IQD", currencyName: "Iraqi Dinar", flag: "🇮🇶", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "JO", name: "Jordan", currency: "JOD", currencyName: "Jordanian Dinar", flag: "🇯🇴", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "LB", name: "Lebanon", currency: "LBP", currencyName: "Lebanese Pound", flag: "🇱🇧", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SY", name: "Syria", currency: "SYP", currencyName: "Syrian Pound", flag: "🇸🇾", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "YE", name: "Yemen", currency: "YER", currencyName: "Yemeni Rial", flag: "🇾🇪", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "OM", name: "Oman", currency: "OMR", currencyName: "Omani Rial", flag: "🇴🇲", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "QA", name: "Qatar", currency: "QAR", currencyName: "Qatari Rial", flag: "🇶🇦", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "BH", name: "Bahrain", currency: "BHD", currencyName: "Bahraini Dinar", flag: "🇧🇭", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "KW", name: "Kuwait", currency: "KWD", currencyName: "Kuwaiti Dinar", flag: "🇰🇼", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "SA", name: "Saudi Arabia", currency: "SAR", currencyName: "Saudi Riyal", flag: "🇸🇦", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "AE", name: "United Arab Emirates", currency: "AED", currencyName: "UAE Dirham", flag: "🇦🇪", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "IL", name: "Israel", currency: "ILS", currencyName: "Israeli Shekel", flag: "🇮🇱", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "PS", name: "Palestine", currency: "ILS", currencyName: "Israeli Shekel", flag: "🇵🇸", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TN", name: "Tunisia", currency: "TND", currencyName: "Tunisian Dinar", flag: "🇹🇳", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "DZ", name: "Algeria", currency: "DZD", currencyName: "Algerian Dinar", flag: "🇩🇿", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "LY", name: "Libya", currency: "LYD", currencyName: "Libyan Dinar", flag: "🇱🇾", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SD", name: "Sudan", currency: "SDG", currencyName: "Sudanese Pound", flag: "🇸🇩", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SS", name: "South Sudan", currency: "SSP", currencyName: "South Sudanese Pound", flag: "🇸🇸", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "ER", name: "Eritrea", currency: "ERN", currencyName: "Eritrean Nakfa", flag: "🇪🇷", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "DJ", name: "Djibouti", currency: "DJF", currencyName: "Djiboutian Franc", flag: "🇩🇯", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SO", name: "Somalia", currency: "SOS", currencyName: "Somali Shilling", flag: "🇸🇴", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MR", name: "Mauritania", currency: "MRU", currencyName: "Mauritanian Ouguiya", flag: "🇲🇷", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "ML", name: "Mali", currency: "XOF", currencyName: "West African CFA Franc", flag: "🇲🇱", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SN", name: "Senegal", currency: "XOF", currencyName: "West African CFA Franc", flag: "🇸🇳", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GM", name: "Gambia", currency: "GMD", currencyName: "Gambian Dalasi", flag: "🇬🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GW", name: "Guinea-Bissau", currency: "XOF", currencyName: "West African CFA Franc", flag: "🇬🇼", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GN", name: "Guinea", currency: "GNF", currencyName: "Guinean Franc", flag: "🇬🇳", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SL", name: "Sierra Leone", currency: "SLL", currencyName: "Sierra Leonean Leone", flag: "🇸🇱", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "LR", name: "Liberia", currency: "LRD", currencyName: "Liberian Dollar", flag: "🇱🇷", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CI", name: "Cote d'Ivoire", currency: "XOF", currencyName: "West African CFA Franc", flag: "🇨🇮", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BF", name: "Burkina Faso", currency: "XOF", currencyName: "West African CFA Franc", flag: "🇧🇫", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "NE", name: "Niger", currency: "XOF", currencyName: "West African CFA Franc", flag: "🇳🇪", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TG", name: "Togo", currency: "XOF", currencyName: "West African CFA Franc", flag: "🇹🇬", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BJ", name: "Benin", currency: "XOF", currencyName: "West African CFA Franc", flag: "🇧🇯", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CM", name: "Cameroon", currency: "XAF", currencyName: "Central African CFA Franc", flag: "🇨🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CF", name: "Central African Republic", currency: "XAF", currencyName: "Central African CFA Franc", flag: "🇨🇫", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TD", name: "Chad", currency: "XAF", currencyName: "Central African CFA Franc", flag: "🇹🇩", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CG", name: "Congo", currency: "XAF", currencyName: "Central African CFA Franc", flag: "🇨🇬", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GA", name: "Gabon", currency: "XAF", currencyName: "Central African CFA Franc", flag: "🇬🇦", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GQ", name: "Equatorial Guinea", currency: "XAF", currencyName: "Central African CFA Franc", flag: "🇬🇶", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AO", name: "Angola", currency: "AOA", currencyName: "Angolan Kwanza", flag: "🇦🇴", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CD", name: "DR Congo", currency: "CDF", currencyName: "Congolese Franc", flag: "🇨🇩", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BI", name: "Burundi", currency: "BIF", currencyName: "Burundian Franc", flag: "🇧🇮", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MZ", name: "Mozambique", currency: "MZN", currencyName: "Mozambican Metical", flag: "🇲🇿", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "ZM", name: "Zambia", currency: "ZMW", currencyName: "Zambian Kwacha", flag: "🇿🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MW", name: "Malawi", currency: "MWK", currencyName: "Malawian Kwacha", flag: "🇲🇼", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "ZW", name: "Zimbabwe", currency: "ZWL", currencyName: "Zimbabwean Dollar", flag: "🇿🇼", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BW", name: "Botswana", currency: "BWP", currencyName: "Botswana Pula", flag: "🇧🇼", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SZ", name: "Eswatini", currency: "SZL", currencyName: "Swazi Lilangeni", flag: "🇸🇿", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "LS", name: "Lesotho", currency: "LSL", currencyName: "Lesotho Loti", flag: "🇱🇸", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "NA", name: "Namibia", currency: "NAD", currencyName: "Namibian Dollar", flag: "🇳🇦", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MG", name: "Madagascar", currency: "MGA", currencyName: "Malagasy Ariary", flag: "🇲🇬", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MU", name: "Mauritius", currency: "MUR", currencyName: "Mauritian Rupee", flag: "🇲🇺", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "SC", name: "Seychelles", currency: "SCR", currencyName: "Seychellois Rupee", flag: "🇸🇨", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "KM", name: "Comoros", currency: "KMF", currencyName: "Comorian Franc", flag: "🇰🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CV", name: "Cape Verde", currency: "CVE", currencyName: "Cape Verdean Escudo", flag: "🇨🇻", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "ST", name: "Sao Tome and Principe", currency: "STN", currencyName: "Sao Tome Dobra", flag: "🇸🇹", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CR", name: "Costa Rica", currency: "CRC", currencyName: "Costa Rican Colon", flag: "🇨🇷", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "PA", name: "Panama", currency: "PAB", currencyName: "Panamanian Balboa", flag: "🇵🇦", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "GT", name: "Guatemala", currency: "GTQ", currencyName: "Guatemalan Quetzal", flag: "🇬🇹", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "HN", name: "Honduras", currency: "HNL", currencyName: "Honduran Lempira", flag: "🇭🇳", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "SV", name: "El Salvador", currency: "USD", currencyName: "US Dollar", flag: "🇸🇻", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "NI", name: "Nicaragua", currency: "NIO", currencyName: "Nicaraguan Cordoba", flag: "🇳🇮", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BZ", name: "Belize", currency: "BZD", currencyName: "Belize Dollar", flag: "🇧🇿", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "JM", name: "Jamaica", currency: "JMD", currencyName: "Jamaican Dollar", flag: "🇯🇲", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "HT", name: "Haiti", currency: "HTG", currencyName: "Haitian Gourde", flag: "🇭🇹", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "DO", name: "Dominican Republic", currency: "DOP", currencyName: "Dominican Peso", flag: "🇩🇴", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "CU", name: "Cuba", currency: "CUP", currencyName: "Cuban Peso", flag: "🇨🇺", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BS", name: "Bahamas", currency: "BSD", currencyName: "Bahamian Dollar", flag: "🇧🇸", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "BB", name: "Barbados", currency: "BBD", currencyName: "Barbadian Dollar", flag: "🇧🇧", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "TT", name: "Trinidad and Tobago", currency: "TTD", currencyName: "Trinidad Dollar", flag: "🇹🇹", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "GD", name: "Grenada", currency: "XCD", currencyName: "East Caribbean Dollar", flag: "🇬🇩", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "LC", name: "Saint Lucia", currency: "XCD", currencyName: "East Caribbean Dollar", flag: "🇱🇨", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "VC", name: "Saint Vincent", currency: "XCD", currencyName: "East Caribbean Dollar", flag: "🇻🇨", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AG", name: "Antigua and Barbuda", currency: "XCD", currencyName: "East Caribbean Dollar", flag: "🇦🇬", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "DM", name: "Dominica", currency: "XCD", currencyName: "East Caribbean Dollar", flag: "🇩🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "KN", name: "Saint Kitts", currency: "XCD", currencyName: "East Caribbean Dollar", flag: "🇰🇳", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GY", name: "Guyana", currency: "GYD", currencyName: "Guyanese Dollar", flag: "🇬🇾", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SR", name: "Suriname", currency: "SRD", currencyName: "Surinamese Dollar", flag: "🇸🇷", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "PY", name: "Paraguay", currency: "PYG", currencyName: "Paraguayan Guarani", flag: "🇵🇾", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BO", name: "Bolivia", currency: "BOB", currencyName: "Bolivian Boliviano", flag: "🇧🇴", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "EC", name: "Ecuador", currency: "USD", currencyName: "US Dollar", flag: "🇪🇨", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "VE", name: "Venezuela", currency: "VES", currencyName: "Venezuelan Bolivar", flag: "🇻🇪", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GF", name: "French Guiana", currency: "EUR", currencyName: "Euro", flag: "🇬🇫", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MQ", name: "Martinique", currency: "EUR", currencyName: "Euro", flag: "🇲🇶", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GP", name: "Guadeloupe", currency: "EUR", currencyName: "Euro", flag: "🇬🇵", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "RE", name: "Reunion", currency: "EUR", currencyName: "Euro", flag: "🇷🇪", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "YT", name: "Mayotte", currency: "EUR", currencyName: "Euro", flag: "🇾🇹", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "PF", name: "French Polynesia", currency: "XPF", currencyName: "CFP Franc", flag: "🇵🇫", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "NC", name: "New Caledonia", currency: "XPF", currencyName: "CFP Franc", flag: "🇳🇨", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "WF", name: "Wallis and Futuna", currency: "XPF", currencyName: "CFP Franc", flag: "🇼🇫", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "PM", name: "Saint Pierre", currency: "EUR", currencyName: "Euro", flag: "🇵🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BL", name: "Saint Barthelemy", currency: "EUR", currencyName: "Euro", flag: "🇧🇱", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MF", name: "Saint Martin", currency: "EUR", currencyName: "Euro", flag: "🇲🇫", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SX", name: "Sint Maarten", currency: "ANG", currencyName: "Netherlands Antillean Guilder", flag: "🇸🇽", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CW", name: "Curacao", currency: "ANG", currencyName: "Netherlands Antillean Guilder", flag: "🇨🇼", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BQ", name: "Bonaire", currency: "USD", currencyName: "US Dollar", flag: "🇧🇶", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AW", name: "Aruba", currency: "AWG", currencyName: "Aruban Florin", flag: "🇦🇼", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "FK", name: "Falkland Islands", currency: "FKP", currencyName: "Falkland Pound", flag: "🇫🇰", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GS", name: "South Georgia", currency: "GBP", currencyName: "British Pound", flag: "🇬🇸", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SH", name: "Saint Helena", currency: "SHP", currencyName: "Saint Helena Pound", flag: "🇸🇭", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AC", name: "Ascension Island", currency: "SHP", currencyName: "Saint Helena Pound", flag: "🇦🇨", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TA", name: "Tristan da Cunha", currency: "GBP", currencyName: "British Pound", flag: "🇹🇦", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "IO", name: "British Indian Ocean", currency: "USD", currencyName: "US Dollar", flag: "🇮🇴", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CC", name: "Cocos Islands", currency: "AUD", currencyName: "Australian Dollar", flag: "🇨🇨", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CX", name: "Christmas Island", currency: "AUD", currencyName: "Australian Dollar", flag: "🇨🇽", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "NF", name: "Norfolk Island", currency: "AUD", currencyName: "Australian Dollar", flag: "🇳🇫", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "HM", name: "Heard Island", currency: "AUD", currencyName: "Australian Dollar", flag: "🇭🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AQ", name: "Antarctica", currency: "USD", currencyName: "US Dollar", flag: "🇦🇶", methodsAvailable: '["bank","cash"]' },
    { code: "AS", name: "American Samoa", currency: "USD", currencyName: "US Dollar", flag: "🇦🇸", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GU", name: "Guam", currency: "USD", currencyName: "US Dollar", flag: "🇬🇺", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MP", name: "Northern Mariana Islands", currency: "USD", currencyName: "US Dollar", flag: "🇲🇵", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "PR", name: "Puerto Rico", currency: "USD", currencyName: "US Dollar", flag: "🇵🇷", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "VI", name: "US Virgin Islands", currency: "USD", currencyName: "US Dollar", flag: "🇻🇮", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "KY", name: "Cayman Islands", currency: "KYD", currencyName: "Cayman Dollar", flag: "🇰🇾", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "BM", name: "Bermuda", currency: "BMD", currencyName: "Bermudian Dollar", flag: "🇧🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AI", name: "Anguilla", currency: "XCD", currencyName: "East Caribbean Dollar", flag: "🇦🇮", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MS", name: "Montserrat", currency: "XCD", currencyName: "East Caribbean Dollar", flag: "🇲🇸", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TC", name: "Turks and Caicos", currency: "USD", currencyName: "US Dollar", flag: "🇹🇨", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "AD", name: "Andorra", currency: "EUR", currencyName: "Euro", flag: "🇦🇩", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MC", name: "Monaco", currency: "EUR", currencyName: "Euro", flag: "🇲🇨", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "SM", name: "San Marino", currency: "EUR", currencyName: "Euro", flag: "🇸🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "VA", name: "Vatican", currency: "EUR", currencyName: "Euro", flag: "🇻🇦", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "LI", name: "Liechtenstein", currency: "CHF", currencyName: "Swiss Franc", flag: "🇱🇮", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "IM", name: "Isle of Man", currency: "GBP", currencyName: "British Pound", flag: "🇮🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "JE", name: "Jersey", currency: "GBP", currencyName: "British Pound", flag: "🇯🇪", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "GG", name: "Guernsey", currency: "GBP", currencyName: "British Pound", flag: "🇬🇬", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MO", name: "Macau", currency: "MOP", currencyName: "Macanese Pataca", flag: "🇲🇴", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "TW", name: "Taiwan", currency: "TWD", currencyName: "New Taiwan Dollar", flag: "🇹🇼", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "BN", name: "Brunei", currency: "BND", currencyName: "Brunei Dollar", flag: "🇧🇳", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "TL", name: "Timor-Leste", currency: "USD", currencyName: "US Dollar", flag: "🇹🇱", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "FM", name: "Micronesia", currency: "USD", currencyName: "US Dollar", flag: "🇫🇲", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "MH", name: "Marshall Islands", currency: "USD", currencyName: "US Dollar", flag: "🇲🇭", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "PW", name: "Palau", currency: "USD", currencyName: "US Dollar", flag: "🇵🇼", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "KI", name: "Kiribati", currency: "AUD", currencyName: "Australian Dollar", flag: "🇰🇮", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "NR", name: "Nauru", currency: "AUD", currencyName: "Australian Dollar", flag: "🇳🇷", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TV", name: "Tuvalu", currency: "AUD", currencyName: "Australian Dollar", flag: "🇹🇻", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TO", name: "Tonga", currency: "TOP", currencyName: "Tongan Pa'anga", flag: "🇹🇴", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "WS", name: "Samoa", currency: "WST", currencyName: "Samoan Tala", flag: "🇼🇸", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "FJ", name: "Fiji", currency: "FJD", currencyName: "Fijian Dollar", flag: "🇫🇯", methodsAvailable: '["bank","cash","mobile","wallet"]' },
    { code: "SB", name: "Solomon Islands", currency: "SBD", currencyName: "Solomon Dollar", flag: "🇸🇧", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "VU", name: "Vanuatu", currency: "VUV", currencyName: "Vanuatu Vatu", flag: "🇻🇺", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "PG", name: "Papua New Guinea", currency: "PGK", currencyName: "Papua Kina", flag: "🇵🇬", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "CK", name: "Cook Islands", currency: "NZD", currencyName: "New Zealand Dollar", flag: "🇨🇰", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "NU", name: "Niue", currency: "NZD", currencyName: "New Zealand Dollar", flag: "🇳🇺", methodsAvailable: '["bank","cash","mobile"]' },
    { code: "TK", name: "Tokelau", currency: "NZD", currencyName: "New Zealand Dollar", flag: "🇹🇰", methodsAvailable: '["bank","cash","mobile"]' },
  ];

  for (const country of countries) {
    await db.insert(supportedCountries).values(country).onDuplicateKeyUpdate({
      set: { name: country.name, currency: country.currency, flag: country.flag, methodsAvailable: country.methodsAvailable },
    });
  }
  console.log("Countries seeded");
}

async function main() {
  console.log("Seeding database...");
  await seedExchangeRates();
  await seedCountries();
  console.log("Done!");
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
